# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Documents\Gitee\yuanShenEx\Launcher\res\Launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LauncherWindow(object):
    def setupUi(self, LauncherWindow):
        LauncherWindow.setObjectName("LauncherWindow")
        LauncherWindow.resize(981, 570)
        self.Main_Widget = QtWidgets.QWidget(LauncherWindow)
        self.Main_Widget.setObjectName("Main_Widget")
        self.Top_Frame = QtWidgets.QFrame(self.Main_Widget)
        self.Top_Frame.setGeometry(QtCore.QRect(10, 10, 961, 31))
        self.Top_Frame.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    color: rgb(244, 216, 135);\n"
"}\n"
"QFrame {\n"
"    \n"
"    background-color: rgb(20, 20, 20);\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"\n"
"\n"
"}\n"
"")
        self.Top_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Frame.setObjectName("Top_Frame")
        self.Title_Lable = QtWidgets.QLabel(self.Top_Frame)
        self.Title_Lable.setGeometry(QtCore.QRect(10, 0, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Lable.setFont(font)
        self.Title_Lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title_Lable.setObjectName("Title_Lable")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Top_Frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(880, 0, 80, 30))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.Top_Right_Layout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.Top_Right_Layout.setContentsMargins(0, 0, 5, 0)
        self.Top_Right_Layout.setSpacing(10)
        self.Top_Right_Layout.setObjectName("Top_Right_Layout")
        self.Min_Bottom = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Min_Bottom.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255 ,95);\n"
"}")
        self.Min_Bottom.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Min_Bottom.setIcon(icon)
        self.Min_Bottom.setIconSize(QtCore.QSize(20, 20))
        self.Min_Bottom.setObjectName("Min_Bottom")
        self.Top_Right_Layout.addWidget(self.Min_Bottom)
        self.Close_Buttom = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Close_Buttom.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0 ,95);\n"
"}")
        self.Close_Buttom.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_Buttom.setIcon(icon1)
        self.Close_Buttom.setIconSize(QtCore.QSize(20, 20))
        self.Close_Buttom.setObjectName("Close_Buttom")
        self.Top_Right_Layout.addWidget(self.Close_Buttom)
        self.MainFrame = QtWidgets.QFrame(self.Main_Widget)
        self.MainFrame.setGeometry(QtCore.QRect(10, 40, 961, 521))
        self.MainFrame.setStyleSheet("background-color: rgba(20, 20, 20, 95);")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.APPFrame = QtWidgets.QFrame(self.MainFrame)
        self.APPFrame.setGeometry(QtCore.QRect(0, 0, 231, 521))
        self.APPFrame.setStyleSheet("QScrollArea {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none；\n"
"}\n"
"\n"
"QLabel {    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    background-origin: content;\n"
"    background-position: left;\n"
"    background-repeat: no-repeat;\n"
"    text-align: center;\n"
"    border:none;\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{    \n"
"    border:none;\n"
"    background-color: rgb(255, 255, 255 );\n"
"    color: rgb(0, 0, 0 );\n"
"}")
        self.APPFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.APPFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.APPFrame.setObjectName("APPFrame")
        self.APP_Icon = QtWidgets.QPushButton(self.APPFrame)
        self.APP_Icon.setGeometry(QtCore.QRect(60, 0, 41, 41))
        self.APP_Icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.APP_Icon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.APP_Icon.setIcon(icon2)
        self.APP_Icon.setObjectName("APP_Icon")
        self.APP_Title_Label = QtWidgets.QLabel(self.APPFrame)
        self.APP_Title_Label.setGeometry(QtCore.QRect(103, 4, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.APP_Title_Label.setFont(font)
        self.APP_Title_Label.setStyleSheet("color: rgb(255, 255, 255);")
        self.APP_Title_Label.setObjectName("APP_Title_Label")
        self.APP_ScrollArea_2 = QtWidgets.QScrollArea(self.APPFrame)
        self.APP_ScrollArea_2.setGeometry(QtCore.QRect(50, 40, 181, 471))
        self.APP_ScrollArea_2.setStyleSheet("QWidget#APP_ScrollArea {\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none；\n"
"}")
        self.APP_ScrollArea_2.setWidgetResizable(True)
        self.APP_ScrollArea_2.setObjectName("APP_ScrollArea_2")
        self.APP_ScrollArea = QtWidgets.QWidget()
        self.APP_ScrollArea.setGeometry(QtCore.QRect(0, 0, 181, 471))
        self.APP_ScrollArea.setObjectName("APP_ScrollArea")
        self.APP_Map_PushButton = QtWidgets.QPushButton(self.APP_ScrollArea)
        self.APP_Map_PushButton.setGeometry(QtCore.QRect(0, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.APP_Map_PushButton.setFont(font)
        self.APP_Map_PushButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.APP_Map_PushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.APP_Map_PushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.APP_Map_PushButton.setStyleSheet("QPushButton\n"
"{    \n"
"    background-origin: content;\n"
"    background-position: left;\n"
"    background-repeat: no-repeat;\n"
"    padding-left:10px;\n"
"    text-align: left;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/app_icon/Map.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.APP_Map_PushButton.setIcon(icon3)
        self.APP_Map_PushButton.setIconSize(QtCore.QSize(25, 25))
        self.APP_Map_PushButton.setAutoRepeatDelay(300)
        self.APP_Map_PushButton.setAutoDefault(False)
        self.APP_Map_PushButton.setObjectName("APP_Map_PushButton")
        self.APP_GenShinAutoPlayer_PushButton = QtWidgets.QPushButton(self.APP_ScrollArea)
        self.APP_GenShinAutoPlayer_PushButton.setGeometry(QtCore.QRect(0, 0, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.APP_GenShinAutoPlayer_PushButton.setFont(font)
        self.APP_GenShinAutoPlayer_PushButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.APP_GenShinAutoPlayer_PushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.APP_GenShinAutoPlayer_PushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.APP_GenShinAutoPlayer_PushButton.setStyleSheet("QPushButton\n"
"{    \n"
"    background-origin: content;\n"
"    background-position: left;\n"
"    background-repeat: no-repeat;\n"
"    padding-left:10px;\n"
"    text-align: left;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/app_icon/Genshin_auto_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.APP_GenShinAutoPlayer_PushButton.setIcon(icon4)
        self.APP_GenShinAutoPlayer_PushButton.setIconSize(QtCore.QSize(25, 25))
        self.APP_GenShinAutoPlayer_PushButton.setAutoRepeatDelay(300)
        self.APP_GenShinAutoPlayer_PushButton.setAutoDefault(False)
        self.APP_GenShinAutoPlayer_PushButton.setObjectName("APP_GenShinAutoPlayer_PushButton")
        self.APP_GenShinAutoPlayer_PushButton.raise_()
        self.APP_Map_PushButton.raise_()
        self.APP_ScrollArea_2.setWidget(self.APP_ScrollArea)
        self.APP_ScrollArea_2.raise_()
        self.APP_Icon.raise_()
        self.APP_Title_Label.raise_()
        self.Background_Label = QtWidgets.QLabel(self.MainFrame)
        self.Background_Label.setGeometry(QtCore.QRect(0, -30, 961, 551))
        self.Background_Label.setStyleSheet("border-image: url(:/background/background.png);\n"
"border-radius:10px;\n"
"")
        self.Background_Label.setText("")
        self.Background_Label.setObjectName("Background_Label")
        self.SetFrame = QtWidgets.QFrame(self.MainFrame)
        self.SetFrame.setGeometry(QtCore.QRect(0, 0, 391, 521))
        self.SetFrame.setStyleSheet("QLabel {    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    background-origin: content;\n"
"    background-position: left;\n"
"    background-repeat: no-repeat;\n"
"    text-align: center;\n"
"    border:none;\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{    \n"
"    border:none;\n"
"    background-color: rgb(255, 255, 255 );\n"
"    color: rgb(0, 0, 0 );\n"
"}")
        self.SetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SetFrame.setObjectName("SetFrame")
        self.Set_Icon = QtWidgets.QPushButton(self.SetFrame)
        self.Set_Icon.setGeometry(QtCore.QRect(50, 0, 41, 41))
        self.Set_Icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.Set_Icon.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Set_Icon.setIcon(icon5)
        self.Set_Icon.setObjectName("Set_Icon")
        self.Set_Title_Lable = QtWidgets.QLabel(self.SetFrame)
        self.Set_Title_Lable.setGeometry(QtCore.QRect(93, 4, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Set_Title_Lable.setFont(font)
        self.Set_Title_Lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.Set_Title_Lable.setObjectName("Set_Title_Lable")
        self.scrollArea = QtWidgets.QScrollArea(self.SetFrame)
        self.scrollArea.setGeometry(QtCore.QRect(50, 40, 331, 471))
        self.scrollArea.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.Set_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.Set_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 331, 471))
        self.Set_scrollAreaWidgetContents.setObjectName("Set_scrollAreaWidgetContents")
        self.SetRun_GroupBox = QtWidgets.QGroupBox(self.Set_scrollAreaWidgetContents)
        self.SetRun_GroupBox.setGeometry(QtCore.QRect(0, 10, 321, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.SetRun_GroupBox.setFont(font)
        self.SetRun_GroupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.SetRun_GroupBox.setObjectName("SetRun_GroupBox")
        self.RunAndExit_RadioButton = QtWidgets.QRadioButton(self.SetRun_GroupBox)
        self.RunAndExit_RadioButton.setGeometry(QtCore.QRect(30, 80, 221, 21))
        self.RunAndExit_RadioButton.setObjectName("RunAndExit_RadioButton")
        self.RunAndMin_RadioButton = QtWidgets.QRadioButton(self.SetRun_GroupBox)
        self.RunAndMin_RadioButton.setGeometry(QtCore.QRect(30, 50, 171, 21))
        self.RunAndMin_RadioButton.setObjectName("RunAndMin_RadioButton")
        self.RunAndNot_RadioButton = QtWidgets.QRadioButton(self.SetRun_GroupBox)
        self.RunAndNot_RadioButton.setGeometry(QtCore.QRect(30, 20, 171, 21))
        self.RunAndNot_RadioButton.setObjectName("RunAndNot_RadioButton")
        self.GamePath_GroupBox = QtWidgets.QGroupBox(self.Set_scrollAreaWidgetContents)
        self.GamePath_GroupBox.setGeometry(QtCore.QRect(0, 270, 321, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.GamePath_GroupBox.setFont(font)
        self.GamePath_GroupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.GamePath_GroupBox.setObjectName("GamePath_GroupBox")
        self.GamePath_LineEdit = QtWidgets.QLineEdit(self.GamePath_GroupBox)
        self.GamePath_LineEdit.setGeometry(QtCore.QRect(10, 30, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.GamePath_LineEdit.setFont(font)
        self.GamePath_LineEdit.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.GamePath_LineEdit.setObjectName("GamePath_LineEdit")
        self.GamePathLook_Button = QtWidgets.QPushButton(self.GamePath_GroupBox)
        self.GamePathLook_Button.setGeometry(QtCore.QRect(230, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.GamePathLook_Button.setFont(font)
        self.GamePathLook_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.GamePathLook_Button.setObjectName("GamePathLook_Button")
        self.ToolPath_GroupBox = QtWidgets.QGroupBox(self.Set_scrollAreaWidgetContents)
        self.ToolPath_GroupBox.setGeometry(QtCore.QRect(0, 360, 331, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.ToolPath_GroupBox.setFont(font)
        self.ToolPath_GroupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.ToolPath_GroupBox.setObjectName("ToolPath_GroupBox")
        self.LookToolPath_Button = QtWidgets.QPushButton(self.ToolPath_GroupBox)
        self.LookToolPath_Button.setGeometry(QtCore.QRect(220, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.LookToolPath_Button.setFont(font)
        self.LookToolPath_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.LookToolPath_Button.setObjectName("LookToolPath_Button")
        self.SelectTool_ComboBox = QtWidgets.QComboBox(self.ToolPath_GroupBox)
        self.SelectTool_ComboBox.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.SelectTool_ComboBox.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.SelectTool_ComboBox.setObjectName("SelectTool_ComboBox")
        self.SelectTool_ComboBox.addItem("")
        self.SelectTool_ComboBox.addItem("")
        self.ToolPath_LineEdit = QtWidgets.QLineEdit(self.ToolPath_GroupBox)
        self.ToolPath_LineEdit.setGeometry(QtCore.QRect(10, 73, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ToolPath_LineEdit.setFont(font)
        self.ToolPath_LineEdit.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.ToolPath_LineEdit.setObjectName("ToolPath_LineEdit")
        self.DownToolButton = QtWidgets.QPushButton(self.ToolPath_GroupBox)
        self.DownToolButton.setGeometry(QtCore.QRect(220, 28, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.DownToolButton.setFont(font)
        self.DownToolButton.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.DownToolButton.setObjectName("DownToolButton")
        self.AccountManger_RoupBox = QtWidgets.QGroupBox(self.Set_scrollAreaWidgetContents)
        self.AccountManger_RoupBox.setGeometry(QtCore.QRect(0, 130, 321, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.AccountManger_RoupBox.setFont(font)
        self.AccountManger_RoupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.AccountManger_RoupBox.setObjectName("AccountManger_RoupBox")
        self.SelectAccount_ComboBox = QtWidgets.QComboBox(self.AccountManger_RoupBox)
        self.SelectAccount_ComboBox.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.SelectAccount_ComboBox.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.SelectAccount_ComboBox.setObjectName("SelectAccount_ComboBox")
        self.DelAcconut_Button = QtWidgets.QPushButton(self.AccountManger_RoupBox)
        self.DelAcconut_Button.setGeometry(QtCore.QRect(220, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.DelAcconut_Button.setFont(font)
        self.DelAcconut_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.DelAcconut_Button.setObjectName("DelAcconut_Button")
        self.ADDAconut_Button = QtWidgets.QPushButton(self.AccountManger_RoupBox)
        self.ADDAconut_Button.setGeometry(QtCore.QRect(10, 72, 311, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.ADDAconut_Button.setFont(font)
        self.ADDAconut_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.ADDAconut_Button.setObjectName("ADDAconut_Button")
        self.scrollArea.setWidget(self.Set_scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.Set_Icon.raise_()
        self.Set_Title_Lable.raise_()
        self.FixedFrame = QtWidgets.QFrame(self.MainFrame)
        self.FixedFrame.setGeometry(QtCore.QRect(0, 0, 361, 521))
        self.FixedFrame.setStyleSheet("QLabel {    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    background-origin: content;\n"
"    background-position: left;\n"
"    background-repeat: no-repeat;\n"
"    text-align: center;\n"
"    border:none;\n"
"\n"
"}\n"
"QPushButton:hover\n"
"{    \n"
"    border:none;\n"
"    background-color: rgb(255, 255, 255 );\n"
"    color: rgb(0, 0, 0 );\n"
"}")
        self.FixedFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FixedFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FixedFrame.setObjectName("FixedFrame")
        self.Fixed_Icon = QtWidgets.QPushButton(self.FixedFrame)
        self.Fixed_Icon.setGeometry(QtCore.QRect(47, 0, 41, 41))
        self.Fixed_Icon.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.Fixed_Icon.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ico/fixed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Fixed_Icon.setIcon(icon6)
        self.Fixed_Icon.setObjectName("Fixed_Icon")
        self.Fixed_Title_Lable = QtWidgets.QLabel(self.FixedFrame)
        self.Fixed_Title_Lable.setGeometry(QtCore.QRect(90, 4, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Fixed_Title_Lable.setFont(font)
        self.Fixed_Title_Lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.Fixed_Title_Lable.setObjectName("Fixed_Title_Lable")
        self.Fixed_ScrollArea = QtWidgets.QScrollArea(self.FixedFrame)
        self.Fixed_ScrollArea.setGeometry(QtCore.QRect(50, 40, 311, 451))
        self.Fixed_ScrollArea.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border:none")
        self.Fixed_ScrollArea.setWidgetResizable(True)
        self.Fixed_ScrollArea.setObjectName("Fixed_ScrollArea")
        self.Fixed_scrollAreaWidge = QtWidgets.QWidget()
        self.Fixed_scrollAreaWidge.setGeometry(QtCore.QRect(0, 0, 311, 451))
        self.Fixed_scrollAreaWidge.setObjectName("Fixed_scrollAreaWidge")
        self.UpdateLauncherSrc_GroupBox = QtWidgets.QGroupBox(self.Fixed_scrollAreaWidge)
        self.UpdateLauncherSrc_GroupBox.setGeometry(QtCore.QRect(0, 10, 311, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.UpdateLauncherSrc_GroupBox.setFont(font)
        self.UpdateLauncherSrc_GroupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.UpdateLauncherSrc_GroupBox.setObjectName("UpdateLauncherSrc_GroupBox")
        self.UpdateLauncherSrc_Download_Button = QtWidgets.QPushButton(self.UpdateLauncherSrc_GroupBox)
        self.UpdateLauncherSrc_Download_Button.setGeometry(QtCore.QRect(150, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.UpdateLauncherSrc_Download_Button.setFont(font)
        self.UpdateLauncherSrc_Download_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.UpdateLauncherSrc_Download_Button.setObjectName("UpdateLauncherSrc_Download_Button")
        self.UpdateLauncherSrc_Path_LineEdit = QtWidgets.QLineEdit(self.UpdateLauncherSrc_GroupBox)
        self.UpdateLauncherSrc_Path_LineEdit.setGeometry(QtCore.QRect(10, 30, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.UpdateLauncherSrc_Path_LineEdit.setFont(font)
        self.UpdateLauncherSrc_Path_LineEdit.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.UpdateLauncherSrc_Path_LineEdit.setObjectName("UpdateLauncherSrc_Path_LineEdit")
        self.UpdateLauncherSrc_Look_Button = QtWidgets.QPushButton(self.UpdateLauncherSrc_GroupBox)
        self.UpdateLauncherSrc_Look_Button.setGeometry(QtCore.QRect(210, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.UpdateLauncherSrc_Look_Button.setFont(font)
        self.UpdateLauncherSrc_Look_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.UpdateLauncherSrc_Look_Button.setObjectName("UpdateLauncherSrc_Look_Button")
        self.GameFixed_GroupBox = QtWidgets.QGroupBox(self.Fixed_scrollAreaWidge)
        self.GameFixed_GroupBox.setGeometry(QtCore.QRect(0, 260, 321, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.GameFixed_GroupBox.setFont(font)
        self.GameFixed_GroupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.GameFixed_GroupBox.setObjectName("GameFixed_GroupBox")
        self.GameFixed_Fixed_Button = QtWidgets.QPushButton(self.GameFixed_GroupBox)
        self.GameFixed_Fixed_Button.setGeometry(QtCore.QRect(210, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.GameFixed_Fixed_Button.setFont(font)
        self.GameFixed_Fixed_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.GameFixed_Fixed_Button.setObjectName("GameFixed_Fixed_Button")
        self.GameFixed_Mode_ComboBox = QtWidgets.QComboBox(self.GameFixed_GroupBox)
        self.GameFixed_Mode_ComboBox.setGeometry(QtCore.QRect(10, 30, 191, 31))
        self.GameFixed_Mode_ComboBox.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.GameFixed_Mode_ComboBox.setObjectName("GameFixed_Mode_ComboBox")
        self.UpdateGuoJiFuSrc_GroupBox = QtWidgets.QGroupBox(self.Fixed_scrollAreaWidge)
        self.UpdateGuoJiFuSrc_GroupBox.setGeometry(QtCore.QRect(0, 130, 311, 121))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.UpdateGuoJiFuSrc_GroupBox.setFont(font)
        self.UpdateGuoJiFuSrc_GroupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.UpdateGuoJiFuSrc_GroupBox.setObjectName("UpdateGuoJiFuSrc_GroupBox")
        self.UpdateGuoJiFuSrc_Look_Button = QtWidgets.QPushButton(self.UpdateGuoJiFuSrc_GroupBox)
        self.UpdateGuoJiFuSrc_Look_Button.setGeometry(QtCore.QRect(210, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.UpdateGuoJiFuSrc_Look_Button.setFont(font)
        self.UpdateGuoJiFuSrc_Look_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.UpdateGuoJiFuSrc_Look_Button.setObjectName("UpdateGuoJiFuSrc_Look_Button")
        self.UpdateGuoJiFuSrc_Path_LineEdit = QtWidgets.QLineEdit(self.UpdateGuoJiFuSrc_GroupBox)
        self.UpdateGuoJiFuSrc_Path_LineEdit.setGeometry(QtCore.QRect(10, 30, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.UpdateGuoJiFuSrc_Path_LineEdit.setFont(font)
        self.UpdateGuoJiFuSrc_Path_LineEdit.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.UpdateGuoJiFuSrc_Path_LineEdit.setText("")
        self.UpdateGuoJiFuSrc_Path_LineEdit.setObjectName("UpdateGuoJiFuSrc_Path_LineEdit")
        self.UpdateGuoJiFuSrc_Download_Button = QtWidgets.QPushButton(self.UpdateGuoJiFuSrc_GroupBox)
        self.UpdateGuoJiFuSrc_Download_Button.setGeometry(QtCore.QRect(160, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.UpdateGuoJiFuSrc_Download_Button.setFont(font)
        self.UpdateGuoJiFuSrc_Download_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.UpdateGuoJiFuSrc_Download_Button.setObjectName("UpdateGuoJiFuSrc_Download_Button")
        self.Report_GroupBox = QtWidgets.QGroupBox(self.Fixed_scrollAreaWidge)
        self.Report_GroupBox.setGeometry(QtCore.QRect(0, 360, 321, 131))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.Report_GroupBox.setFont(font)
        self.Report_GroupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.Report_GroupBox.setObjectName("Report_GroupBox")
        self.Report_Report_Button = QtWidgets.QPushButton(self.Report_GroupBox)
        self.Report_Report_Button.setGeometry(QtCore.QRect(160, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.Report_Report_Button.setFont(font)
        self.Report_Report_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.Report_Report_Button.setObjectName("Report_Report_Button")
        self.Report_OpenLog_Button = QtWidgets.QPushButton(self.Report_GroupBox)
        self.Report_OpenLog_Button.setGeometry(QtCore.QRect(10, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.Report_OpenLog_Button.setFont(font)
        self.Report_OpenLog_Button.setStyleSheet("border: 2px solid white;\n"
"border-radius: 4px;")
        self.Report_OpenLog_Button.setObjectName("Report_OpenLog_Button")
        self.Fixed_ScrollArea.setWidget(self.Fixed_scrollAreaWidge)
        self.Left_Frame = QtWidgets.QFrame(self.MainFrame)
        self.Left_Frame.setGeometry(QtCore.QRect(0, 0, 50, 520))
        self.Left_Frame.setStyleSheet("QFrame{\n"
"    background-color: rgba(20, 20, 20 ,30);\n"
"    border-bottom-left-radius: 10px;\n"
"\n"
"}\n"
"QPushButton {\n"
"    border-radius: 4px;\n"
"    background-color: rgba(20, 20, 20 ,95);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"\n"
"}")
        self.Left_Frame.setObjectName("Left_Frame")
        self.APP_Button = QtWidgets.QPushButton(self.Left_Frame)
        self.APP_Button.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.APP_Button.setText("")
        self.APP_Button.setIcon(icon2)
        self.APP_Button.setObjectName("APP_Button")
        self.Fixed_Button = QtWidgets.QPushButton(self.Left_Frame)
        self.Fixed_Button.setGeometry(QtCore.QRect(10, 70, 31, 31))
        self.Fixed_Button.setText("")
        self.Fixed_Button.setIcon(icon6)
        self.Fixed_Button.setObjectName("Fixed_Button")
        self.Set_Button = QtWidgets.QPushButton(self.Left_Frame)
        self.Set_Button.setGeometry(QtCore.QRect(10, 120, 31, 31))
        self.Set_Button.setText("")
        self.Set_Button.setIcon(icon5)
        self.Set_Button.setObjectName("Set_Button")
        self.Background_Label.raise_()
        self.FixedFrame.raise_()
        self.SetFrame.raise_()
        self.APPFrame.raise_()
        self.Left_Frame.raise_()
        self.Start_Frame = QtWidgets.QFrame(self.Main_Widget)
        self.Start_Frame.setGeometry(QtCore.QRect(670, 400, 231, 111))
        self.Start_Frame.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.Start_Frame.setObjectName("Start_Frame")
        self.Start_PushButton = QtWidgets.QPushButton(self.Start_Frame)
        self.Start_PushButton.setGeometry(QtCore.QRect(10, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Start_PushButton.setFont(font)
        self.Start_PushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 200, 31);\n"
"    border-radius:5\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(185, 144, 22);\n"
"    border-radius:5\n"
"\n"
"}")
        self.Start_PushButton.setDefault(False)
        self.Start_PushButton.setFlat(False)
        self.Start_PushButton.setObjectName("Start_PushButton")
        self.Mode_ComboBox = QtWidgets.QComboBox(self.Start_Frame)
        self.Mode_ComboBox.setGeometry(QtCore.QRect(10, 70, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mode_ComboBox.sizePolicy().hasHeightForWidth())
        self.Mode_ComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Mode_ComboBox.setFont(font)
        self.Mode_ComboBox.setStyleSheet("QWidget {\n"
"    background-color: rgba(20, 20, 20, 0);\n"
"    border-radius:6px;\n"
"}\n"
"QComboBox{\n"
"    background-color: rgba(20, 20, 20, 80);\n"
"    border-radius:6px;\n"
"    padding-left: 5px;    \n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QComboBox:hover{\n"
"    padding-left: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    margin:5px;\n"
"    background-color: transparent ;\n"
"    border-radius:6px;\n"
"    color: rgb(85, 170, 255);\n"
"    outline: 0px solid gray;\n"
"    border:    0px solid transparent;\n"
"    border-radius:6px;\n"
"\n"
"}")
        self.Mode_ComboBox.setFrame(False)
        self.Mode_ComboBox.setObjectName("Mode_ComboBox")
        self.Mode_ComboBox.addItem("")
        self.Mode_ComboBox.addItem("")
        self.Mode_ComboBox.addItem("")
        self.Mode_ComboBox.addItem("")
        self.Acconut_ComboBox = QtWidgets.QComboBox(self.Start_Frame)
        self.Acconut_ComboBox.setGeometry(QtCore.QRect(120, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.Acconut_ComboBox.setFont(font)
        self.Acconut_ComboBox.setStyleSheet("QComboBox{\n"
"    background-color: rgba(20, 20, 20, 80);\n"
"    border-radius:6px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color:white;\n"
"}\n"
"QComboBox:hover{\n"
"\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    padding: 10px;\n"
"    border-radius:6px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.Acconut_ComboBox.setObjectName("Acconut_ComboBox")
        self.Acconut_ComboBox.addItem("")
        self.MainFrame.raise_()
        self.Top_Frame.raise_()
        self.Start_Frame.raise_()
        LauncherWindow.setCentralWidget(self.Main_Widget)

        self.retranslateUi(LauncherWindow)
        QtCore.QMetaObject.connectSlotsByName(LauncherWindow)

    def retranslateUi(self, LauncherWindow):
        _translate = QtCore.QCoreApplication.translate
        LauncherWindow.setWindowTitle(_translate("LauncherWindow", "MainWindow"))
        self.Title_Lable.setText(_translate("LauncherWindow", "原神Ex"))
        self.APP_Title_Label.setText(_translate("LauncherWindow", "工具箱"))
        self.APP_Map_PushButton.setText(_translate("LauncherWindow", "    空莹酒馆原神地图"))
        self.APP_GenShinAutoPlayer_PushButton.setText(_translate("LauncherWindow", "    原琴工具箱"))
        self.Set_Title_Lable.setText(_translate("LauncherWindow", "设置"))
        self.SetRun_GroupBox.setTitle(_translate("LauncherWindow", "启动设置"))
        self.RunAndExit_RadioButton.setText(_translate("LauncherWindow", "启动游戏时,关闭原神Ex"))
        self.RunAndMin_RadioButton.setText(_translate("LauncherWindow", "启动游戏时,最小化原神Ex"))
        self.RunAndNot_RadioButton.setText(_translate("LauncherWindow", "启动游戏时,无操作"))
        self.GamePath_GroupBox.setTitle(_translate("LauncherWindow", "游戏位置设置"))
        self.GamePathLook_Button.setText(_translate("LauncherWindow", "定位游戏"))
        self.ToolPath_GroupBox.setTitle(_translate("LauncherWindow", "工具位置设置"))
        self.LookToolPath_Button.setText(_translate("LauncherWindow", "修改工具位置"))
        self.SelectTool_ComboBox.setItemText(0, _translate("LauncherWindow", "原琴工具箱"))
        self.SelectTool_ComboBox.setItemText(1, _translate("LauncherWindow", "空莹酒馆元神地图"))
        self.DownToolButton.setText(_translate("LauncherWindow", "下载"))
        self.AccountManger_RoupBox.setTitle(_translate("LauncherWindow", "账号管理"))
        self.DelAcconut_Button.setText(_translate("LauncherWindow", "删除"))
        self.ADDAconut_Button.setText(_translate("LauncherWindow", "添加"))
        self.Fixed_Title_Lable.setText(_translate("LauncherWindow", "一键修复"))
        self.UpdateLauncherSrc_GroupBox.setTitle(_translate("LauncherWindow", "更新资源"))
        self.UpdateLauncherSrc_Download_Button.setText(_translate("LauncherWindow", "一键更新"))
        self.UpdateLauncherSrc_Look_Button.setText(_translate("LauncherWindow", "定位资源"))
        self.GameFixed_GroupBox.setTitle(_translate("LauncherWindow", "游戏报错修复"))
        self.GameFixed_Fixed_Button.setText(_translate("LauncherWindow", "修复"))
        self.UpdateGuoJiFuSrc_GroupBox.setTitle(_translate("LauncherWindow", "国际服资源"))
        self.UpdateGuoJiFuSrc_Look_Button.setText(_translate("LauncherWindow", "定位资源"))
        self.UpdateGuoJiFuSrc_Download_Button.setText(_translate("LauncherWindow", "下载"))
        self.Report_GroupBox.setTitle(_translate("LauncherWindow", "反馈"))
        self.Report_Report_Button.setText(_translate("LauncherWindow", "提交问题"))
        self.Report_OpenLog_Button.setText(_translate("LauncherWindow", "打开启动器日志文件夹"))
        self.Start_PushButton.setText(_translate("LauncherWindow", "开始游戏"))
        self.Mode_ComboBox.setItemText(0, _translate("LauncherWindow", "请选择模式"))
        self.Mode_ComboBox.setItemText(1, _translate("LauncherWindow", "启动B服"))
        self.Mode_ComboBox.setItemText(2, _translate("LauncherWindow", "启动国际服"))
        self.Mode_ComboBox.setItemText(3, _translate("LauncherWindow", "启动官服"))
        self.Acconut_ComboBox.setItemText(0, _translate("LauncherWindow", "请选择账号"))
import res_rc
