# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Documents\Gitee\yuanShenEx\Launcher\res\Launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LauncherWindow(object):
    def setupUi(self, LauncherWindow):
        LauncherWindow.setObjectName("LauncherWindow")
        LauncherWindow.resize(986, 570)
        self.Main_Widget = QtWidgets.QWidget(LauncherWindow)
        self.Main_Widget.setObjectName("Main_Widget")
        self.Top_Frame = QtWidgets.QFrame(self.Main_Widget)
        self.Top_Frame.setGeometry(QtCore.QRect(20, 20, 961, 31))
        self.Top_Frame.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    color: rgb(244, 216, 135);\n"
"}\n"
"QFrame {\n"
"    \n"
"    background-color: rgb(20, 20, 20);\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"\n"
"\n"
"}\n"
"")
        self.Top_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Frame.setObjectName("Top_Frame")
        self.Title_Lable = QtWidgets.QLabel(self.Top_Frame)
        self.Title_Lable.setGeometry(QtCore.QRect(10, 0, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Lable.setFont(font)
        self.Title_Lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title_Lable.setObjectName("Title_Lable")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Top_Frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(880, 0, 80, 30))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.Top_Right_Layout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.Top_Right_Layout.setContentsMargins(0, 0, 5, 0)
        self.Top_Right_Layout.setSpacing(10)
        self.Top_Right_Layout.setObjectName("Top_Right_Layout")
        self.Min_Bottom = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Min_Bottom.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255 ,95);\n"
"}")
        self.Min_Bottom.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Min_Bottom.setIcon(icon)
        self.Min_Bottom.setIconSize(QtCore.QSize(20, 20))
        self.Min_Bottom.setObjectName("Min_Bottom")
        self.Top_Right_Layout.addWidget(self.Min_Bottom)
        self.Close_Buttom = QtWidgets.QPushButton(self.layoutWidget_2)
        self.Close_Buttom.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0 ,95);\n"
"}")
        self.Close_Buttom.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_Buttom.setIcon(icon1)
        self.Close_Buttom.setIconSize(QtCore.QSize(20, 20))
        self.Close_Buttom.setObjectName("Close_Buttom")
        self.Top_Right_Layout.addWidget(self.Close_Buttom)
        self.MainFrame = QtWidgets.QFrame(self.Main_Widget)
        self.MainFrame.setGeometry(QtCore.QRect(20, 50, 961, 521))
        self.MainFrame.setStyleSheet("background-color: rgba(20, 20, 20, 95);")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.AppFrame = QtWidgets.QFrame(self.MainFrame)
        self.AppFrame.setGeometry(QtCore.QRect(0, 0, 231, 521))
        self.AppFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AppFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AppFrame.setObjectName("AppFrame")
        self.Background_Label = QtWidgets.QLabel(self.MainFrame)
        self.Background_Label.setGeometry(QtCore.QRect(0, -30, 961, 551))
        self.Background_Label.setStyleSheet("border-image: url(:/background/background.png);\n"
"border-radius:10px;\n"
"")
        self.Background_Label.setText("")
        self.Background_Label.setObjectName("Background_Label")
        self.Background_Label.raise_()
        self.AppFrame.raise_()
        self.Left_Frame = QtWidgets.QFrame(self.Main_Widget)
        self.Left_Frame.setGeometry(QtCore.QRect(20, 50, 61, 521))
        self.Left_Frame.setStyleSheet("QFrame{\n"
"    background-color: rgba(20, 20, 20 ,30);\n"
"    border-bottom-left-radius: 10px;\n"
"\n"
"}\n"
"QPushButton {\n"
"    border-radius: 4px;\n"
"    background-color: rgba(20, 20, 20 ,95);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"\n"
"}")
        self.Left_Frame.setObjectName("Left_Frame")
        self.APP_PushButton = QtWidgets.QPushButton(self.Left_Frame)
        self.APP_PushButton.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.APP_PushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.APP_PushButton.setIcon(icon2)
        self.APP_PushButton.setObjectName("APP_PushButton")
        self.Set_PushButton_2 = QtWidgets.QPushButton(self.Left_Frame)
        self.Set_PushButton_2.setGeometry(QtCore.QRect(10, 70, 31, 31))
        self.Set_PushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Set_PushButton_2.setIcon(icon3)
        self.Set_PushButton_2.setObjectName("Set_PushButton_2")
        self.Start_Frame = QtWidgets.QFrame(self.Main_Widget)
        self.Start_Frame.setGeometry(QtCore.QRect(680, 410, 231, 111))
        self.Start_Frame.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.Start_Frame.setObjectName("Start_Frame")
        self.Start_PushButton = QtWidgets.QPushButton(self.Start_Frame)
        self.Start_PushButton.setGeometry(QtCore.QRect(10, 10, 211, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Start_PushButton.setFont(font)
        self.Start_PushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 200, 31);\n"
"    border-radius:5\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(185, 144, 22);\n"
"    border-radius:5\n"
"\n"
"}")
        self.Start_PushButton.setDefault(False)
        self.Start_PushButton.setFlat(False)
        self.Start_PushButton.setObjectName("Start_PushButton")
        self.Mode_ComboBox = QtWidgets.QComboBox(self.Start_Frame)
        self.Mode_ComboBox.setGeometry(QtCore.QRect(10, 70, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mode_ComboBox.sizePolicy().hasHeightForWidth())
        self.Mode_ComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Mode_ComboBox.setFont(font)
        self.Mode_ComboBox.setStyleSheet("QComboBox{\n"
"    background-color: rgba(20, 20, 20, 80);\n"
"    border-radius:6px;\n"
"    padding-left: 5px;    \n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"QComboBox:hover{\n"
"    padding-left: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    margin:5px;\n"
"    background-color: transparent ;\n"
"    border-radius:6px;\n"
"    color: rgb(85, 170, 255);\n"
"    outline: 0px solid gray;\n"
"    border:    0px solid transparent;\n"
"    border-radius:6px;\n"
"\n"
"}")
        self.Mode_ComboBox.setFrame(False)
        self.Mode_ComboBox.setObjectName("Mode_ComboBox")
        self.Mode_ComboBox.addItem("")
        self.Mode_ComboBox.addItem("")
        self.Mode_ComboBox.addItem("")
        self.Mode_ComboBox.addItem("")
        self.Acconut_ComboBox = QtWidgets.QComboBox(self.Start_Frame)
        self.Acconut_ComboBox.setGeometry(QtCore.QRect(120, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.Acconut_ComboBox.setFont(font)
        self.Acconut_ComboBox.setStyleSheet("QComboBox{\n"
"    background-color: rgba(20, 20, 20, 80);\n"
"    border-radius:6px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color:white;\n"
"}\n"
"QComboBox:hover{\n"
"\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    padding: 10px;\n"
"    border-radius:6px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.Acconut_ComboBox.setObjectName("Acconut_ComboBox")
        self.Acconut_ComboBox.addItem("")
        LauncherWindow.setCentralWidget(self.Main_Widget)

        self.retranslateUi(LauncherWindow)
        QtCore.QMetaObject.connectSlotsByName(LauncherWindow)

    def retranslateUi(self, LauncherWindow):
        _translate = QtCore.QCoreApplication.translate
        LauncherWindow.setWindowTitle(_translate("LauncherWindow", "MainWindow"))
        self.Title_Lable.setText(_translate("LauncherWindow", "原神Ex"))
        self.Start_PushButton.setText(_translate("LauncherWindow", "开始游戏"))
        self.Mode_ComboBox.setItemText(0, _translate("LauncherWindow", "请选择模式"))
        self.Mode_ComboBox.setItemText(1, _translate("LauncherWindow", "启动B服"))
        self.Mode_ComboBox.setItemText(2, _translate("LauncherWindow", "启动国际服"))
        self.Mode_ComboBox.setItemText(3, _translate("LauncherWindow", "启动官服"))
        self.Acconut_ComboBox.setItemText(0, _translate("LauncherWindow", "请选择账号"))
import res_rc
