# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Documents\GitHub\YuanShenEx_Launcher\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_installer(object):
    def setupUi(self, installer):
        installer.setObjectName("installer")
        installer.setEnabled(True)
        installer.resize(759, 525)
        self.centralwidget = QtWidgets.QWidget(installer)
        self.centralwidget.setObjectName("centralwidget")
        self.MainWidget = QtWidgets.QWidget(self.centralwidget)
        self.MainWidget.setGeometry(QtCore.QRect(20, 10, 730, 500))
        self.MainWidget.setStyleSheet("QPushButton {\n"
                                      "    border:none;\n"
                                      "}\n"
                                      "QPushButton:hove {\n"
                                      "    padding-bottom:5px;\n"
                                      "}\n"
                                      "QWidget{\n"
                                      "    border-radius:5px;\n"
                                      "}")
        self.MainWidget.setObjectName("MainWidget")
        self.Fontground = QtWidgets.QLabel(self.MainWidget)
        self.Fontground.setGeometry(QtCore.QRect(0, 0, 730, 391))
        self.Fontground.setStyleSheet("border-image: url(:/img/background.png);\n"
                                      "border-bottom-right-radius:0px;\n"
                                      "border-bottom-left-radius:0px;")
        self.Fontground.setText("")
        self.Fontground.setObjectName("Fontground")
        self.Title = QtWidgets.QLabel(self.MainWidget)
        self.Title.setGeometry(QtCore.QRect(10, 0, 191, 31))
        font = QtGui.QFont()
        font.setFamily("有爱魔兽圆体 CN")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title.setObjectName("Title")
        self.frame_top_right = QtWidgets.QFrame(self.MainWidget)
        self.frame_top_right.setGeometry(QtCore.QRect(570, 0, 71, 31))
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.InstallerStartButton = QtWidgets.QPushButton(self.MainWidget)
        self.InstallerStartButton.setGeometry(QtCore.QRect(265, 240, 200, 51))
        font = QtGui.QFont()
        font.setFamily("有爱魔兽圆体 CN Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.InstallerStartButton.setFont(font)
        self.InstallerStartButton.setStyleSheet("QPushButton {\n"
                                                "    background-color: rgb(255, 200, 31);\n"
                                                "    border-radius:5px\n"
                                                "}\n"
                                                "QPushButton:pressed {\n"
                                                "    background-color:rgb(185, 144, 22);\n"
                                                "    border-radius:5px\n"
                                                "}")
        self.InstallerStartButton.setObjectName("InstallerStartButton")
        self.Begin_Installer_Frame = QtWidgets.QFrame(self.MainWidget)
        self.Begin_Installer_Frame.setGeometry(QtCore.QRect(0, 330, 730, 100))
        self.Begin_Installer_Frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                                 "border-top-right-radius:0px;\n"
                                                 "border-top-left-radius:0px;")
        self.Begin_Installer_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Begin_Installer_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Begin_Installer_Frame.setObjectName("Begin_Installer_Frame")
        self.Installer_Frame = QtWidgets.QFrame(self.Begin_Installer_Frame)
        self.Installer_Frame.setGeometry(QtCore.QRect(10, 10, 711, 91))
        self.Installer_Frame.setStyleSheet("QPushButton {\n"
                                           "    border:none;\n"
                                           "    border-radius:5px;\n"
                                           "    \n"
                                           "    color: rgb(244, 216, 135);\n"
                                           "    background-color: rgb(57, 59, 64);\n"
                                           "}\n"
                                           "QLineEdit {\n"
                                           "    \n"
                                           "    border: 1px solid gray;\n"
                                           "    border-radius: 5px;\n"
                                           "    padding: 0 8px;\n"
                                           "    selection-background-color: darkgray;\n"
                                           "}\n"
                                           "QFrame {\n"
                                           "    border:none;\n"
                                           "    }")
        self.Installer_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Installer_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Installer_Frame.setObjectName("Installer_Frame")
        self.LookButton = QtWidgets.QPushButton(self.Installer_Frame)
        self.LookButton.setGeometry(QtCore.QRect(570, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("有爱魔兽圆体 CN Medium")
        font.setPointSize(7)
        self.LookButton.setFont(font)
        self.LookButton.setStyleSheet("QPushButton:pressed {\n"
                                      "        \n"
                                      "    background-color: rgb(34, 35, 38);\n"
                                      "}")
        self.LookButton.setObjectName("LookButton")
        self.Path = QtWidgets.QLineEdit(self.Installer_Frame)
        self.Path.setGeometry(QtCore.QRect(30, 40, 521, 31))
        self.Path.setObjectName("Path")
        self.InstallerLabel = QtWidgets.QLabel(self.Installer_Frame)
        self.InstallerLabel.setGeometry(QtCore.QRect(40, 0, 111, 31))
        font = QtGui.QFont()
        font.setFamily("有爱魔兽圆体 CN Medium")
        font.setPointSize(12)
        self.InstallerLabel.setFont(font)
        self.InstallerLabel.setObjectName("InstallerLabel")
        self.layoutWidget = QtWidgets.QWidget(self.MainWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(660, 0, 71, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MinBottom = QtWidgets.QPushButton(self.layoutWidget)
        self.MinBottom.setStyleSheet("QPushButton:hover {\n"
                                     "    background-color: rgb(255, 255, 255 , 95);\n"
                                     "}")
        self.MinBottom.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MinBottom.setIcon(icon)
        self.MinBottom.setIconSize(QtCore.QSize(20, 20))
        self.MinBottom.setObjectName("MinBottom")
        self.horizontalLayout.addWidget(self.MinBottom)
        self.CloseButtom = QtWidgets.QPushButton(self.layoutWidget)
        self.CloseButtom.setStyleSheet("QPushButton:hover {\n"
                                       "    background-color: rgb(255, 0, 0 ， 95);\n"
                                       "}")
        self.CloseButtom.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseButtom.setIcon(icon1)
        self.CloseButtom.setIconSize(QtCore.QSize(20, 20))
        self.CloseButtom.setObjectName("CloseButtom")
        self.horizontalLayout.addWidget(self.CloseButtom)
        self.Fontground.raise_()
        self.Title.raise_()
        self.frame_top_right.raise_()
        self.Begin_Installer_Frame.raise_()
        self.layoutWidget.raise_()
        self.InstallerStartButton.raise_()
        installer.setCentralWidget(self.centralwidget)

        self.retranslateUi(installer)
        self.MinBottom.clicked.connect(installer.showMinimized)
        self.CloseButtom.clicked.connect(installer.close)
        QtCore.QMetaObject.connectSlotsByName(installer)

    def retranslateUi(self, installer):
        _translate = QtCore.QCoreApplication.translate
        installer.setWindowTitle(_translate("installer", "MainWindow"))
        self.Title.setText(_translate("installer", "原神启动器EX安装程序"))
        self.InstallerStartButton.setText(_translate("installer", "立即安装"))
        self.LookButton.setText(_translate("installer", "选择文件位置"))
        self.InstallerLabel.setText(_translate("installer", "安装位置"))
