# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Documents\Gitee\yuanShenEx\installer\Tip.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tip(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 267)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 380, 250))
        self.widget.setObjectName("widget")
        self.Backgroud_Label = QtWidgets.QLabel(self.widget)
        self.Backgroud_Label.setGeometry(QtCore.QRect(0, 0, 380, 250))
        self.Backgroud_Label.setStyleSheet("border-image: url(:/background/Tip.png);")
        self.Backgroud_Label.setText("")
        self.Backgroud_Label.setObjectName("Backgroud_Label")
        self.Title_Label = QtWidgets.QLabel(self.widget)
        self.Title_Label.setGeometry(QtCore.QRect(0, 20, 380, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label.setFont(font)
        self.Title_Label.setMouseTracking(False)
        self.Title_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Label.setObjectName("Title_Label")
        self.Content_Label = QtWidgets.QLabel(self.widget)
        self.Content_Label.setGeometry(QtCore.QRect(0, 80, 380, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Content_Label.setFont(font)
        self.Content_Label.setMouseTracking(False)
        self.Content_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Content_Label.setObjectName("Content_Label")
        self.OK_Button = QtWidgets.QPushButton(self.widget)
        self.OK_Button.setGeometry(QtCore.QRect(130, 190, 125, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.OK_Button.setFont(font)
        self.OK_Button.setStyleSheet("QPushButton:pressed {        \n"
                                     "    background-color: rgb(34, 35, 38);\n"
                                     "}\n"
                                     "QPushButton {\n"
                                     "    border:none;\n"
                                     "    border-radius:5px;\n"
                                     "    \n"
                                     "    color: rgb(244, 216, 135);\n"
                                     "    background-color: rgb(57, 59, 64);\n"
                                     "}")
        self.OK_Button.setObjectName("OK_Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.OK_Button.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title_Label.setText(_translate("MainWindow", "Title"))
        self.Content_Label.setText(_translate("MainWindow", "content"))
        self.OK_Button.setText(_translate("MainWindow", "确认"))


import Tip_rc
